version: "3.7"
services:
  ng-coop-connect-dev:
    build:
      context: .
      dockerfile: "./docker/dev/Dockerfile.dev"
    volumes:
      - ".:/app"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - "4200:4200"
